from google.protobuf import symbol_database as _symbol_database
from google.protobuf import reflection as _reflection
from google.protobuf import message as _message
from google.protobuf import descriptor as _descriptor
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: variablebatch.proto
"""Generated protocol buffer code."""
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='variablebatch.proto',
    package='variablebatch',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x13variablebatch.proto\x12\rvariablebatch\"<\n\x17GetVariableBatchRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0f\n\x07indices\x18\x02 \x03(\x05\":\n\x15GetVariableBatchReply\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0f\n\x07indices\x18\x02 \x03(\x05\x32q\n\rVariableBatch\x12`\n\x10GetVariableBatch\x12&.variablebatch.GetVariableBatchRequest\x1a$.variablebatch.GetVariableBatchReplyb\x06proto3'
)


_GETVARIABLEBATCHREQUEST = _descriptor.Descriptor(
    name='GetVariableBatchRequest',
    full_name='variablebatch.GetVariableBatchRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='hostname', full_name='variablebatch.GetVariableBatchRequest.hostname', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='indices', full_name='variablebatch.GetVariableBatchRequest.indices', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=38,
    serialized_end=98,
)


_GETVARIABLEBATCHREPLY = _descriptor.Descriptor(
    name='GetVariableBatchReply',
    full_name='variablebatch.GetVariableBatchReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='hostname', full_name='variablebatch.GetVariableBatchReply.hostname', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='indices', full_name='variablebatch.GetVariableBatchReply.indices', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=100,
    serialized_end=158,
)

DESCRIPTOR.message_types_by_name['GetVariableBatchRequest'] = _GETVARIABLEBATCHREQUEST
DESCRIPTOR.message_types_by_name['GetVariableBatchReply'] = _GETVARIABLEBATCHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetVariableBatchRequest = _reflection.GeneratedProtocolMessageType('GetVariableBatchRequest', (_message.Message,), {
    'DESCRIPTOR': _GETVARIABLEBATCHREQUEST,
    '__module__': 'variablebatch_pb2'
    # @@protoc_insertion_point(class_scope:variablebatch.GetVariableBatchRequest)
})
_sym_db.RegisterMessage(GetVariableBatchRequest)

GetVariableBatchReply = _reflection.GeneratedProtocolMessageType('GetVariableBatchReply', (_message.Message,), {
    'DESCRIPTOR': _GETVARIABLEBATCHREPLY,
    '__module__': 'variablebatch_pb2'
    # @@protoc_insertion_point(class_scope:variablebatch.GetVariableBatchReply)
})
_sym_db.RegisterMessage(GetVariableBatchReply)


_VARIABLEBATCH = _descriptor.ServiceDescriptor(
    name='VariableBatch',
    full_name='variablebatch.VariableBatch',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=160,
    serialized_end=273,
    methods=[
        _descriptor.MethodDescriptor(
            name='GetVariableBatch',
            full_name='variablebatch.VariableBatch.GetVariableBatch',
            index=0,
            containing_service=None,
            input_type=_GETVARIABLEBATCHREQUEST,
            output_type=_GETVARIABLEBATCHREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_VARIABLEBATCH)

DESCRIPTOR.services_by_name['VariableBatch'] = _VARIABLEBATCH

# @@protoc_insertion_point(module_scope)
